server:
  port: 8080

spring:
  application:
    name: banco-austro

datasources:
  cuenca:
    url: jdbc:postgresql://localhost:5432/banco_cuenca?sslmode=disable
    username: banco
    password: banco123
    driver-class-name: org.postgresql.Driver
  quito:
    url: jdbc:postgresql://localhost:5433/banco_quito?sslmode=disable
    username: banco
    password: banco123
    driver-class-name: org.postgresql.Driver